sudo: required

services:
  - docker

before_install:
  - docker build -t ankurtomar007/complex-app -f ./client/Dockerfile.dev ./client   

script:
  - docker run -e CI=true ankurtomar007/complex-app npm run test

after_success:
    - docker build -t ankurtomar007/multi-nginx ./nginx
    - docker build -t ankurtomar007/multi-client ./client
    - docker build -t ankurtomar007/multi-server ./server
    - docker build -t ankurtomar007/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push ankurtomar007/multi-nginx 
    - docker push ankurtomar007/multi-client 
    - docker push ankurtomar007/multi-server 
    - docker push ankurtomar007/multi-worker 
   