sudo: required

services:
  - docker

before_install:
  - docker build -t ankurtomar007/complex-app -f ./client/Dockerfile.dev ./client   

scripts:
  - docker run -e CI=true ankurtomar007/complex-app npm run text